### ISSUE TITLE
Unit tests Error

### ISSUE THREAD

**Issue by pontikos** [phenopolis/phenogenon#9]
```
root@20e9c1320d8f:/phenogenon# coverage run --omit=*/site-packages/*,*/tests/* -m unittest discover -s tests
.Lines   total/split/realigned/skipped:	711/14/0/0
Lines   total/split/realigned/skipped:	731/0/11/0
561
268
F..Lines   total/split/realigned/skipped:	711/14/0/0
Lines   total/split/realigned/skipped:	731/0/11/0
561
268
E.
======================================================================
ERROR: test_phenogenon (test_phenogenon.PhenogenonTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/phenogenon/tests/test_phenogenon.py", line 142, in test_phenogenon
    C(result, expected)
  File "/phenogenon/tests/test_phenogenon.py", line 125, in C
    C(x[k],y[k])
  File "/phenogenon/tests/test_phenogenon.py", line 125, in C
    C(x[k],y[k])
  File "/phenogenon/tests/test_phenogenon.py", line 125, in C
    C(x[k],y[k])
  File "/phenogenon/tests/test_phenogenon.py", line 128, in C
    C(x[i],y[i])
  File "/phenogenon/tests/test_phenogenon.py", line 128, in C
    C(x[i],y[i])
  File "/phenogenon/tests/test_phenogenon.py", line 131, in C
    raise ValueError('{} != {}'.format(x,y))
ValueError: 0.999999999995 != 1.0

======================================================================
FAIL: test_hgf (test_phenogenon.PhenogenonTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/phenogenon/tests/test_phenogenon.py", line 168, in test_hgf
    self.assertDictEqual(result[key], expected[key])
AssertionError: {'r': {'HP:0007754': 0.7722161828400639}, 'd': {'HP:0007754': 0.7553804238805912 [truncated]... != {u'r': {u'HP:0007754': 0.7722161828401903}, u'd': {u'HP:0007754': 0.755380423880 [truncated]...
- {'d': {'HP:0007754': 0.7553804238805912},
?                                     ^^

+ {u'd': {u'HP:0007754': 0.7553804238805425},
?  +      +                             ^ +

-  'r': {'HP:0007754': 0.7722161828400639}}
?                                     - -

+  u'r': {u'HP:0007754': 0.7722161828401903}}
?  +      +                            ++


----------------------------------------------------------------------
Ran 6 tests in 113.245s

FAILED (failures=1, errors=1)
```

**Comment by logust79** [comment]
should solve in pull https://github.com/phenopolis/phenogenon/pull/10

**Comment by logust79** [comment]
should be solved with commit https://github.com/phenopolis/phenogenon/commit/28a3b50d6e0dbb64afb31880efc663bc690bf54b

**Comment by pontikos** [comment]
I concur `self not defined error` @logust79 .
